#pragma once
#include <stdint.h>

// AI: below section was generated by an AI
// TI INA219 SBOS448G: shunt register 0x01 is signed, with a 10 uV LSB.
// https://www.ti.com/lit/ds/symlink/ina219.pdf
// Default preserves the existing 10 mOhm extension board. A3 R8 uses 3000 uOhm.
#ifndef INA219_LAMP_SHUNT_UOHM
#define INA219_LAMP_SHUNT_UOHM 10000
#endif
static_assert(INA219_LAMP_SHUNT_UOHM > 0, "INA219 shunt resistance must be positive");

namespace Ina219Lamp {
constexpr float SHUNT_OHMS = INA219_LAMP_SHUNT_UOHM * 1e-6f;

// Convert the raw two's-complement shunt register, including reverse current.
inline float currentAmps(uint16_t raw) {
  const int32_t signedRaw = raw < 0x8000u ? raw : static_cast<int32_t>(raw) - 65536;
  return signedRaw * 10e-6f / SHUNT_OHMS;
}
}
// AI: end
