// AI: below section was generated by an AI
#include "../usermods/ina219_lamp/ina219_shunt.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>

// Exercise every register bit pattern against an independent double reference.
int main() {
  for (unsigned raw = 0; raw <= 65535; ++raw) {
    const int signedValue = raw < 32768 ? int(raw) : int(raw) - 65536;
    const double expected = signedValue * 10.0 / INA219_LAMP_SHUNT_UOHM;
    assert(fabs(Ina219Lamp::currentAmps(raw) - expected) < 0.00003);
  }
  assert(Ina219Lamp::currentAmps(0) == 0);
  assert(Ina219Lamp::currentAmps(0xffff) < 0);
  const unsigned at4p6A = INA219_LAMP_SHUNT_UOHM == 3000 ? 1380 : 4600;
  assert(fabs(Ina219Lamp::currentAmps(at4p6A) - 4.6) < 0.000001);
  printf("PASS: %d uOhm, 65536 raw codes, forward/reverse/zero, 4.6 A\n", INA219_LAMP_SHUNT_UOHM);
}
// AI: end
